// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/4/2024, 19:58:24
const configMerger = require("D:/web/portfolio-web/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["D:/web/portfolio-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/web/portfolio-web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/web/portfolio-web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/web/portfolio-web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/web/portfolio-web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/web/portfolio-web/plugins/**/*.{js,ts,mjs}","D:/web/portfolio-web/composables/**/*.{js,ts,mjs}","D:/web/portfolio-web/utils/**/*.{js,ts,mjs}","D:/web/portfolio-web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/web/portfolio-web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/web/portfolio-web/app.config.{js,ts,mjs}"] }));

module.exports = config
